name: Push components to Espressif Component Service

# on:
#     push:
#       branches:
#         - main

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Upload components to component service
        uses: espressif/upload-components-ci-action@v1
        with:
          directories: >
            components/vibramotor;
          namespace: "hope-badge"
          api_token: ${{ secrets.CM_TOKEN }}
